In [2]:
import json
import pickle 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
import sys

# Simulation

In [14]:
# #DEBUGGING:
# os.path.exists('./logfiles/241220_120215_0_data.txt')

In [15]:
# Load Data
filename = '241220_120215_0'
data = np.loadtxt('./logfiles/{}_data.txt'.format(filename), delimiter=',')

In [20]:
data.shape


(321, 16)

In [21]:
data[0]

array([-1884.83,     0.  ,     0.  ,     0.  , -2107.67, -1002.55,
           6.46,     2.46,     0.  ,     0.  ,     0.  ,     0.  ,
           0.  ,     0.  ,     0.  ,     0.  ])

In [47]:
arena_list = [6000,6000,2000] # 6x6x2 m cylindrical arena
arena = np.array(arena_list)

no_fish = 2
pos = np.zeros((no_fish, 4))

leader_initial = [-3000, 0]
# Standard Surface Initialization
initial_spread = 3000 # radius
pos = np.zeros((no_fish, 4))
vel = np.zeros((no_fish, 4))
theta = np.random.rand(no_fish) * np.pi * 2 
r = np.random.rand(no_fish) * initial_spread 
# pos[:,:2] = initial_spread * (np.random.rand(no_fish, 2) - 0.5) #+ arena_center[:2] # x,y
pos[:,0] = r * np.cos(theta) + leader_initial[0]
pos[:,1] = r * np.sin(theta) + leader_initial[1]
pos[:,2] = 10 * np.random.rand(1, no_fish) # z, all fish at same noise-free depth results in LJ lock
pos[:,3] = 2* np.pi * (np.random.rand(1, no_fish) - 0.5) # phi

# fix leader pos sort of center at the middle, this can be further overwritten in the experiment file
pos[0,0] = leader_initial[0] #arena_center[:2] 
pos[0,1] = leader_initial[1]
pos[0,2] = 0
pos[0,3] = 0

In [48]:
print(pos)
print()

[[-3.00000000e+03  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.44246905e+03  1.61975424e+03  4.25244314e+00 -1.19698861e+00]]



In [49]:
arena_size = arena

r = np.linalg.norm(pos[:2], axis = 1)
print("r is," , r)
pos[:,0] = pos[:,0]/r*np.clip(r, 0, arena_size[0]/2)
pos[:,1] = pos[:,1]/r*np.clip(r, 0, arena_size[0]/2)    


r is, [3000.         2930.74706602]


In [50]:
pos[:,0]

array([-3000.        , -2442.46904948])

In [51]:
pos

array([[-3.00000000e+03,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.44246905e+03,  1.61975424e+03,  4.25244314e+00,
        -1.19698861e+00]])

In [40]:
pos[:,0]

array([-2221.06299962, -1172.03175773])